/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2026-06-13-0cf9169"
#endif /* AVUTIL_FFVERSION_H */
